"""Tests for the `ydk ci` command group."""

from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING

import pytest
from typer.testing import CliRunner

from ydk.cli import app
from ydk.core import ci_generator
from ydk.core.ci_generator import CiTarget

if TYPE_CHECKING:
    from pathlib import Path

runner = CliRunner()

HINT = "Re-run with --force to overwrite skipped files."
WARNING = "may not exist"


@pytest.fixture
def repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A tmp repo with a github config and one fixture template registered."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / ".ydk").mkdir()
    (tmp_path / ".ydk" / "config.yaml").write_text("project:\n  name: demo\n  remote: github\n", encoding="utf-8")
    tdir = tmp_path / "tpl"
    tdir.mkdir()
    (tdir / "demo.yml").write_text("name: demo {{YDK_VERSION}}\n", encoding="utf-8")
    monkeypatch.setattr(ci_generator, "TEMPLATES_DIR", tdir)
    monkeypatch.setattr(ci_generator, "CI_TARGETS", [CiTarget("demo.yml", "demo.yml", "Demo purpose")])
    monkeypatch.setattr(ci_generator, "select_stack_target", lambda stack: None)
    monkeypatch.setattr(ci_generator.importlib.metadata, "version", lambda name: "1.5.0")
    return tmp_path


def test_ci_help() -> None:
    assert runner.invoke(app, ["ci", "--help"]).exit_code == 0
    result = runner.invoke(app, ["ci", "init", "--help"])
    assert result.exit_code == 0
    # Typer forces a rich terminal under GITHUB_ACTIONS, styling "-" and "-force" separately.
    assert "--force" in re.sub(r"\x1b\[[0-9;]*m", "", result.output)


def test_missing_config_exits_1(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["ci", "init"])
    assert result.exit_code == 1
    assert "config.yaml" in result.output
    assert not (tmp_path / ".github").exists()


def test_non_github_remote_exits_1(repo: Path) -> None:
    (repo / ".ydk" / "config.yaml").write_text("project:\n  name: demo\n  remote: local\n", encoding="utf-8")
    result = runner.invoke(app, ["ci", "init"])
    assert result.exit_code == 1
    assert "github" in result.output
    assert not (repo / ".github").exists()


def test_fresh_then_idempotent(repo: Path) -> None:
    first = runner.invoke(app, ["ci", "init"])
    assert first.exit_code == 0, first.output
    assert "written" in first.output
    assert "Demo purpose" in first.output
    assert HINT not in first.output
    assert WARNING not in first.output

    files = [repo / ".github" / "workflows" / "demo.yml", repo / ".github" / "PULL_REQUEST_TEMPLATE.md"]
    before = {p: (p.read_bytes(), p.stat().st_mtime_ns) for p in files}
    second = runner.invoke(app, ["ci", "init"])
    assert second.exit_code == 0
    assert "skipped (exists)" in second.output
    assert HINT in second.output
    assert {p: (p.read_bytes(), p.stat().st_mtime_ns) for p in files} == before


def test_force_overwrites(repo: Path) -> None:
    runner.invoke(app, ["ci", "init"])
    wf = repo / ".github" / "workflows" / "demo.yml"
    wf.write_text("custom", encoding="utf-8")
    result = runner.invoke(app, ["ci", "init", "--force"])
    assert result.exit_code == 0
    assert "overwritten" in result.output
    assert wf.read_text(encoding="utf-8").startswith("# Generated by ydk ci init v1.5.0.")


def test_json_output(repo: Path) -> None:
    result = runner.invoke(app, ["--format", "json", "ci", "init"])
    assert result.exit_code == 0
    data = json.loads(result.output)
    assert data == {
        "written": [".github/workflows/demo.yml", ".github/PULL_REQUEST_TEMPLATE.md"],
        "skipped": [],
    }
    again = json.loads(runner.invoke(app, ["--format", "json", "ci", "init"]).output)
    assert again["written"] == []
    assert len(again["skipped"]) == 2


@pytest.fixture
def python_repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A tmp repo with a github python-cli config and the real shipped templates."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / ".ydk").mkdir()
    (tmp_path / ".ydk" / "config.yaml").write_text(
        "project:\n  name: demo\n  remote: github\n  stack: python-cli\n", encoding="utf-8"
    )
    monkeypatch.setattr(ci_generator.importlib.metadata, "version", lambda name: "1.5.0")
    return tmp_path


def test_python_stack_summary_and_missing_uv_lock_warning(python_repo: Path) -> None:
    result = runner.invoke(app, ["ci", "init"])
    assert result.exit_code == 0, result.output
    assert (python_repo / ".github" / "workflows" / "ci.yml").is_file()
    assert "stack CI (python)" in result.output
    assert "uv.lock" in result.output


def test_python_stack_with_uv_lock_no_warning(python_repo: Path) -> None:
    (python_repo / "uv.lock").write_text("", encoding="utf-8")
    result = runner.invoke(app, ["ci", "init"])
    assert result.exit_code == 0, result.output
    assert (python_repo / ".github" / "workflows" / "ci.yml").is_file()
    assert "uv.lock" not in result.output


def test_dev_version_warns(repo: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(ci_generator.importlib.metadata, "version", lambda name: "1.5.0.dev3")
    result = runner.invoke(app, ["ci", "init"])
    assert result.exit_code == 0
    assert WARNING in result.output
    assert "v1.5.0.dev3" in result.output


def test_fallback_stack_summary(python_repo: Path) -> None:
    (python_repo / ".ydk" / "config.yaml").write_text(
        "project:\n  name: demo\n  remote: github\n  stack: terraform\n", encoding="utf-8"
    )
    result = runner.invoke(app, ["ci", "init"])
    assert result.exit_code == 0, result.output
    assert (python_repo / ".github" / "workflows" / "ci.yml").is_file()
    assert "stack CI (fallback: verify run)" in result.output
    assert "uv.lock" not in result.output
