"""CI workflow generator — renders package-data templates into `.github/workflows/`.

Pure render/write logic behind `ydk ci init`; the CLI layer only formats the result.
Later tasks add workflows by appending a `CiTarget` to `CI_TARGETS` and dropping a
template file into `src/ydk/templates/ci/`.
"""

from __future__ import annotations

import importlib.metadata
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from ydk.core.config import load_config

if TYPE_CHECKING:
    from collections.abc import Callable, Mapping, Sequence

TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates" / "ci"
WORKFLOWS_DIR = Path(".github") / "workflows"
PR_TEMPLATE_PATH = Path(".github") / "PULL_REQUEST_TEMPLATE.md"

HEADER = "# Generated by ydk ci init v{version}. Re-run 'ydk ci init --force' to regenerate.\n"

PR_TEMPLATE = """\
## Changes


## Verification Proof

<!-- YDK fills this in automatically -->

## Spec refs


Closes #
"""

WRITTEN = "written"
OVERWRITTEN = "overwritten"
SKIPPED = "skipped (exists)"


class CiConfigError(Exception):
    """Raised when the project is not configured for CI generation."""


@dataclass(frozen=True)
class CiContext:
    """Values substituted into templates."""

    version: str
    stack: str
    spec_location: str
    components_path: str
    schemas_path: str


def _always(_ctx: CiContext) -> bool:
    return True


@dataclass(frozen=True)
class CiTarget:
    """One generated workflow: template file, output name under `.github/workflows/`, purpose, condition."""

    template: str
    output: str
    purpose: str
    condition: Callable[[CiContext], bool] = field(default=_always)


# Registry of generated workflows.
CI_TARGETS: list[CiTarget] = [
    CiTarget("ydk-pr-body.yml", "ydk-pr-body.yml", "PR body validation"),
    CiTarget("ydk-pr-checks.yml", "ydk-pr-checks.yml", "Branch name and conventional commit checks"),
    CiTarget(
        template="ydk-delete-merged-branch.yml",
        output="ydk-delete-merged-branch.yml",
        purpose="Delete head branch after merge",
    ),
    CiTarget("ydk-sync.yml", "ydk-sync.yml", "Post-merge task and issue sync"),
]

PYTHON_CI = CiTarget(template="ci-python.yml", output="ci.yml", purpose="stack CI (python)")
DOTNET_CI = CiTarget(template="ci-dotnet.yml", output="ci.yml", purpose="stack CI (dotnet)")

FALLBACK_CI = CiTarget(template="ci-fallback.yml", output="ci.yml", purpose="stack CI (fallback: verify run)")

# `project.stack` -> stack CI target written as `ci.yml`. Unlisted stacks get FALLBACK_CI.
STACK_CI_TARGETS: dict[str, CiTarget] = {
    "python-fastapi": PYTHON_CI,
    "python-cli": PYTHON_CI,
    "dotnet": DOTNET_CI,
}

SOLUTION_WARNING = (
    'Could not detect a single .sln/.slnx file; ci.yml has SOLUTION: "". Set the SOLUTION env var in ci.yml.'
)

UV_LOCK_WARNING = "uv.lock not found at the repo root; ci.yml runs 'uv sync --locked' and fails until it is committed."


def detect_solution(root: Path) -> str:
    """Return the single `.sln`/`.slnx` at *root*, else the single one one level down; "" if zero or several."""

    def _slns(directory: Path) -> list[Path]:
        return sorted(p for p in directory.iterdir() if p.is_file() and p.suffix in (".sln", ".slnx"))

    found = _slns(root)
    if not found:
        for sub in sorted(p for p in root.iterdir() if p.is_dir() and not p.name.startswith(".")):
            found.extend(_slns(sub))
    return found[0].relative_to(root).as_posix() if len(found) == 1 else ""


def select_stack_target(stack: str) -> CiTarget | None:
    """Return the stack CI target for *stack*: its own template, else the fallback."""
    return STACK_CI_TARGETS.get(stack, FALLBACK_CI)


@dataclass(frozen=True)
class CiFileResult:
    """Outcome for a single generated file."""

    path: str
    action: str
    purpose: str


@dataclass(frozen=True)
class CiInitResult:
    """Outcome of a `generate_ci` run."""

    version: str
    files: list[CiFileResult]
    warnings: list[str] = field(default_factory=list)

    @property
    def unpublished(self) -> bool:
        """True when the pinned version tag may not exist (dev or local build)."""
        return not is_release_version(self.version)

    @property
    def written(self) -> list[str]:
        """Paths written or overwritten."""
        return [f.path for f in self.files if f.action in (WRITTEN, OVERWRITTEN)]

    @property
    def skipped(self) -> list[str]:
        """Paths left untouched because they already existed."""
        return [f.path for f in self.files if f.action == SKIPPED]


def is_release_version(version: str) -> bool:
    """A release version has no `dev` segment and no `+local` segment."""
    return "dev" not in version and "+" not in version


def render(template_text: str, ctx: CiContext, extra: Mapping[str, str] | None = None) -> str:
    """Prepend the header and substitute `{{PLACEHOLDER}}` tokens. Deterministic."""
    values = {
        **(extra or {}),
        "YDK_VERSION": ctx.version,
        "STACK": ctx.stack,
        "SPEC_LOCATION": ctx.spec_location,
        "COMPONENTS_PATH": ctx.components_path,
        "SCHEMAS_PATH": ctx.schemas_path,
    }
    body = re.sub(r"\{\{([A-Z_]+)\}\}", lambda m: values.get(m.group(1), m.group(0)), template_text)
    return HEADER.format(version=ctx.version) + body


def _write(root: Path, rel: Path, content: str, purpose: str, *, force: bool) -> CiFileResult:
    target = root / rel
    existed = target.exists()
    if existed and not force:
        return CiFileResult(rel.as_posix(), SKIPPED, purpose)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8", newline="\n")
    return CiFileResult(rel.as_posix(), OVERWRITTEN if existed else WRITTEN, purpose)


def generate_ci(
    root: Path,
    *,
    force: bool,
    version: str | None = None,
    targets: Sequence[CiTarget] | None = None,
    templates_dir: Path | None = None,
) -> CiInitResult:
    """Render and write the CI target set plus the PR template under *root*.

    Raises CiConfigError (writing nothing) when `.ydk/config.yaml` is missing or
    `project.remote` is not `github`.
    """
    config_path = root / ".ydk" / "config.yaml"
    if not config_path.is_file():
        msg = f"{config_path.as_posix()} not found. Run 'ydk init --remote github' first."
        raise CiConfigError(msg)
    config = load_config(config_path)
    if config.project.remote != "github":
        msg = f"project.remote is '{config.project.remote}'; ydk ci init requires remote 'github'."
        raise CiConfigError(msg)

    ctx = CiContext(
        version=version or importlib.metadata.version("ydk"),
        stack=config.project.stack,
        spec_location=config.project.spec_location,
        components_path=config.components.components_path,
        schemas_path=config.components.schemas_path,
    )
    if targets is None:
        stack_target = select_stack_target(ctx.stack)
        targets = [*CI_TARGETS, *([stack_target] if stack_target else [])]
    tdir = templates_dir or TEMPLATES_DIR
    files: list[CiFileResult] = []
    warnings: list[str] = []
    for t in targets:
        if not t.condition(ctx):
            continue
        extra: dict[str, str] | None = None
        if t is DOTNET_CI:
            solution = detect_solution(root)
            if not solution:
                warnings.append(SOLUTION_WARNING)
            version_line = (
                "global-json-file: global.json" if (root / "global.json").is_file() else "dotnet-version: 8.0.x"
            )
            extra = {"SOLUTION": solution, "DOTNET_VERSION_LINE": version_line}
        content = render((tdir / t.template).read_text(encoding="utf-8"), ctx, extra)
        files.append(_write(root, WORKFLOWS_DIR / t.output, content, t.purpose, force=force))
        if t is PYTHON_CI and not (root / "uv.lock").is_file():
            warnings.append(UV_LOCK_WARNING)
    files.append(_write(root, PR_TEMPLATE_PATH, PR_TEMPLATE, "Pull request template", force=force))
    return CiInitResult(version=ctx.version, files=files, warnings=warnings)
