#!/usr/bin/env python3
"""
Generator: auth-provider
Generates a complete Cognito PKCE auth provider from app-config component.

Input: YDK_COMPONENTS_PAGE (looks for auth config in page metadata)
       or YDK_ARTIFACT_APP_CONFIG (explicit app config file)
Output: Auth provider, protected route, config, token storage, callback handler

Deferred-safe: prints [] and exits 0 when config is missing or auth is disabled.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import yaml


def _generate_auth_config(auth: dict) -> str:
    """Generate auth-config.ts — singleton config from env vars."""
    provider = auth.get("provider", "cognito")
    scopes = auth.get("scopes", ["openid", "email", "profile"])
    scopes_str = " ".join(scopes)
    refresh_before = auth.get("refresh_before_expiry_seconds", 60)
    callback_route = auth.get("callback_route", "/auth/callback")
    storage = auth.get("storage", "localStorage")
    token_prefix = auth.get("token_prefix", "app")

    return f"""// Generated by YDK ignition
// Auth configuration singleton — reads from environment variables.

export interface AuthConfig {{
  provider: '{provider}';
  domain: string;
  clientId: string;
  userPoolId: string;
  redirectUri: string;
  scopes: string;
  refreshBeforeExpiryMs: number;
  callbackRoute: string;
  storage: Storage;
  tokenPrefix: string;
}}

function getAuthConfig(): AuthConfig {{
  const domain = process.env.NEXT_PUBLIC_AUTH_DOMAIN ?? '';
  const clientId = process.env.NEXT_PUBLIC_AUTH_CLIENT_ID ?? '';
  const userPoolId = process.env.NEXT_PUBLIC_AUTH_USER_POOL_ID ?? '';

  if (!domain || !clientId) {{
    // Auth is optional — disabled when env vars are not set
    return {{
      provider: '{provider}',
      domain: '',
      clientId: '',
      userPoolId: '',
      redirectUri: '',
      scopes: '{scopes_str}',
      refreshBeforeExpiryMs: {refresh_before * 1000},
      callbackRoute: '{callback_route}',
      storage: {storage},
      tokenPrefix: '{token_prefix}',
    }};
  }}

  const redirectUri =
    typeof window !== 'undefined'
      ? `${{window.location.origin}}{callback_route}`
      : '';

  return {{
    provider: '{provider}',
    domain,
    clientId,
    userPoolId,
    redirectUri,
    scopes: '{scopes_str}',
    refreshBeforeExpiryMs: {refresh_before * 1000},
    callbackRoute: '{callback_route}',
    storage: {storage},
    tokenPrefix: '{token_prefix}',
  }};
}}

let _config: AuthConfig | null = null;

export function authConfig(): AuthConfig {{
  if (!_config) {{
    _config = getAuthConfig();
  }}
  return _config;
}}

export function isAuthEnabled(): boolean {{
  return !!authConfig().clientId;
}}
"""


def _generate_auth_token(auth: dict) -> str:
    """Generate auth-token.ts — module-level token storage for non-React code."""
    storage = auth.get("storage", "localStorage")

    return f"""// Generated by YDK ignition
// Module-level token storage — use getAccessToken() from non-React code.

import {{ authConfig }} from './auth-config';

const TOKEN_KEYS = {{
  access: () => `${{authConfig().tokenPrefix}}_access_token`,
  refresh: () => `${{authConfig().tokenPrefix}}_refresh_token`,
  id: () => `${{authConfig().tokenPrefix}}_id_token`,
  expiry: () => `${{authConfig().tokenPrefix}}_token_expiry`,
}};

export function getAccessToken(): string | null {{
  if (typeof window === 'undefined') return null;
  return {storage}.getItem(TOKEN_KEYS.access());
}}

export function getRefreshToken(): string | null {{
  if (typeof window === 'undefined') return null;
  return {storage}.getItem(TOKEN_KEYS.refresh());
}}

export function getIdToken(): string | null {{
  if (typeof window === 'undefined') return null;
  return {storage}.getItem(TOKEN_KEYS.id());
}}

export function getTokenExpiry(): number {{
  if (typeof window === 'undefined') return 0;
  const raw = {storage}.getItem(TOKEN_KEYS.expiry());
  return raw ? Number.parseInt(raw, 10) : 0;
}}

export function setTokens(access: string, refresh: string, id: string, expiresIn: number): void {{
  const expiry = Date.now() + expiresIn * 1000;
  {storage}.setItem(TOKEN_KEYS.access(), access);
  {storage}.setItem(TOKEN_KEYS.refresh(), refresh);
  {storage}.setItem(TOKEN_KEYS.id(), id);
  {storage}.setItem(TOKEN_KEYS.expiry(), String(expiry));
}}

export function clearTokens(): void {{
  {storage}.removeItem(TOKEN_KEYS.access());
  {storage}.removeItem(TOKEN_KEYS.refresh());
  {storage}.removeItem(TOKEN_KEYS.id());
  {storage}.removeItem(TOKEN_KEYS.expiry());
}}

export function isTokenExpired(): boolean {{
  const expiry = getTokenExpiry();
  return expiry > 0 && Date.now() >= expiry;
}}
"""


def _generate_auth_provider(auth: dict) -> str:
    """Generate auth-provider.tsx — Context provider with PKCE, token refresh, session restore."""
    public_routes = auth.get("public_routes", ["/auth", "/docs"])
    public_routes_str = ", ".join(f"'{r}'" for r in public_routes)

    return f"""// Generated by YDK ignition
'use client';

import {{
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
}} from 'react';
import type {{ ReactNode }} from 'react';
import {{ authConfig, isAuthEnabled }} from './auth-config';
import {{
  clearTokens,
  getAccessToken,
  getRefreshToken,
  getTokenExpiry,
  setTokens,
}} from './auth-token';

interface AuthContextValue {{
  isAuthenticated: boolean;
  isLoading: boolean;
  user: {{ email?: string }} | null;
  login: () => void;
  logout: () => void;
}}

const AuthContext = createContext<AuthContextValue>({{
  isAuthenticated: false,
  isLoading: true,
  user: null,
  login: () => {{}},
  logout: () => {{}},
}});

export function useAuth(): AuthContextValue {{
  return useContext(AuthContext);
}}

// PKCE helpers
function generateCodeVerifier(): string {{
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return btoa(String.fromCharCode(...array))
    .replace(/\\+/g, '-')
    .replace(/\\//g, '_')
    .replace(/=/g, '');
}}

async function generateCodeChallenge(verifier: string): Promise<string> {{
  const encoder = new TextEncoder();
  const data = encoder.encode(verifier);
  const hash = await crypto.subtle.digest('SHA-256', data);
  return btoa(String.fromCharCode(...new Uint8Array(hash)))
    .replace(/\\+/g, '-')
    .replace(/\\//g, '_')
    .replace(/=/g, '');
}}

export function AuthProvider({{ children }}: {{ children: ReactNode }}) {{
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [user, setUser] = useState<{{ email?: string }} | null>(null);
  const refreshTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const config = authConfig();

  const scheduleRefresh = useCallback(() => {{
    if (refreshTimer.current) clearTimeout(refreshTimer.current);
    const expiry = getTokenExpiry();
    const delay = expiry - Date.now() - config.refreshBeforeExpiryMs;
    if (delay <= 0) return;

    refreshTimer.current = setTimeout(async () => {{
      const refreshToken = getRefreshToken();
      if (!refreshToken) return;

      try {{
        const res = await fetch(
          `https://${{config.domain}}/oauth2/token`,
          {{
            method: 'POST',
            headers: {{ 'Content-Type': 'application/x-www-form-urlencoded' }},
            body: new URLSearchParams({{
              grant_type: 'refresh_token',
              client_id: config.clientId,
              refresh_token: refreshToken,
            }}),
          }}
        );
        if (res.ok) {{
          const data = await res.json();
          setTokens(
            data.access_token,
            refreshToken,
            data.id_token,
            data.expires_in
          );
          scheduleRefresh();
        }} else {{
          clearTokens();
          setIsAuthenticated(false);
          setUser(null);
        }}
      }} catch {{
        // Silent failure — next request will trigger re-auth
      }}
    }}, delay);
  }}, [config]);

  // Session restore on mount
  useEffect(() => {{
    if (!isAuthEnabled()) {{
      setIsLoading(false);
      setIsAuthenticated(true); // No auth = always authenticated
      return;
    }}

    const token = getAccessToken();
    if (token) {{
      setIsAuthenticated(true);
      // Parse user from ID token (JWT payload)
      try {{
        const payload = JSON.parse(atob(token.split('.')[1]));
        setUser({{ email: payload.email }});
      }} catch {{
        setUser(null);
      }}
      scheduleRefresh();
    }}
    setIsLoading(false);

    return () => {{
      if (refreshTimer.current) clearTimeout(refreshTimer.current);
    }};
  }}, [scheduleRefresh]);

  const login = useCallback(async () => {{
    const verifier = generateCodeVerifier();
    const challenge = await generateCodeChallenge(verifier);
    sessionStorage.setItem('pkce_verifier', verifier);

    const params = new URLSearchParams({{
      response_type: 'code',
      client_id: config.clientId,
      redirect_uri: config.redirectUri,
      scope: config.scopes,
      code_challenge_method: 'S256',
      code_challenge: challenge,
    }});

    window.location.href = `https://${{config.domain}}/oauth2/authorize?${{params}}`;
  }}, [config]);

  const logout = useCallback(() => {{
    clearTokens();
    if (refreshTimer.current) clearTimeout(refreshTimer.current);
    setIsAuthenticated(false);
    setUser(null);

    const params = new URLSearchParams({{
      client_id: config.clientId,
      logout_uri: window.location.origin,
    }});
    window.location.href = `https://${{config.domain}}/logout?${{params}}`;
  }}, [config]);

  const value = useMemo(
    () => ({{ isAuthenticated, isLoading, user, login, logout }}),
    [isAuthenticated, isLoading, user, login, logout]
  );

  return <AuthContext.Provider value={{value}}>{{children}}</AuthContext.Provider>;
}}

export const PUBLIC_ROUTES = [{public_routes_str}];
"""


def _generate_protected_route(auth: dict) -> str:
    """Generate protected-route.tsx — guard component."""
    return """// Generated by YDK ignition
'use client';

import { usePathname } from 'next/navigation';
import type { ReactNode } from 'react';
import { useAuth, PUBLIC_ROUTES } from './auth-provider';
import { isAuthEnabled } from './auth-config';

export function ProtectedRoute({ children }: { children: ReactNode }) {
  const { isAuthenticated, isLoading, login } = useAuth();
  const pathname = usePathname();

  // Auth disabled — render children directly
  if (!isAuthEnabled()) return <>{children}</>;

  // Check if current route is public
  const isPublic = PUBLIC_ROUTES.some((route) => pathname.startsWith(route));
  if (isPublic) return <>{children}</>;

  // Loading state
  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    );
  }

  // Not authenticated — trigger login
  if (!isAuthenticated) {
    login();
    return (
      <div className="flex items-center justify-center min-h-screen">
        <p>Redirecting to login...</p>
      </div>
    );
  }

  return <>{children}</>;
}
"""


def _generate_callback_page() -> str:
    """Generate callback page.tsx — dynamic import wrapper (ssr: false)."""
    return """// Generated by YDK ignition
import dynamic from 'next/dynamic';

const CallbackHandler = dynamic(() => import('./callback-handler'), {
  ssr: false,
});

export default function AuthCallbackPage() {
  return <CallbackHandler />;
}
"""


def _generate_callback_handler(auth: dict) -> str:
    """Generate callback-handler.tsx — token exchange logic."""
    return """// Generated by YDK ignition
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { authConfig } from '@/shared/lib/auth/auth-config';
import { setTokens } from '@/shared/lib/auth/auth-token';

export default function CallbackHandler() {
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const code = params.get('code');
    const verifier = sessionStorage.getItem('pkce_verifier');

    if (!code || !verifier) {
      setError('Missing authorization code or PKCE verifier');
      return;
    }

    const config = authConfig();

    fetch(`https://${config.domain}/oauth2/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        grant_type: 'authorization_code',
        client_id: config.clientId,
        redirect_uri: config.redirectUri,
        code,
        code_verifier: verifier,
      }),
    })
      .then((res) => {
        if (!res.ok) throw new Error(`Token exchange failed: ${res.status}`);
        return res.json();
      })
      .then((data) => {
        setTokens(
          data.access_token,
          data.refresh_token,
          data.id_token,
          data.expires_in
        );
        sessionStorage.removeItem('pkce_verifier');
        router.replace('/');
      })
      .catch((err) => {
        setError(err.message);
      });
  }, [router]);

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen gap-4">
        <p className="text-destructive">Authentication error: {error}</p>
        <a href="/" className="underline">Return home</a>
      </div>
    );
  }

  return (
    <div className="flex items-center justify-center min-h-screen">
      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      <p className="ml-4">Completing sign-in...</p>
    </div>
  );
}
"""


def _generate_index() -> str:
    """Generate barrel index.ts."""
    return """// Generated by YDK ignition
export { AuthProvider, useAuth, PUBLIC_ROUTES } from './auth-provider';
export { ProtectedRoute } from './protected-route';
export { authConfig, isAuthEnabled } from './auth-config';
export { getAccessToken, clearTokens } from './auth-token';
"""


def main() -> None:
    # Try explicit app config artifact
    artifact_path = os.environ.get("YDK_ARTIFACT_APP_CONFIG", "")
    if not artifact_path or not Path(artifact_path).exists():
        # Deferred — no config artifact
        print(json.dumps([]))
        return

    data = yaml.safe_load(Path(artifact_path).read_text(encoding="utf-8")) or {}
    auth = data.get("auth", {})

    if not auth or auth.get("provider", "none") == "none":
        print(json.dumps([]))
        return

    output = []

    # Auth module files
    output.append({"path": "shared/lib/auth/auth-config.ts", "content": _generate_auth_config(auth)})
    output.append({"path": "shared/lib/auth/auth-token.ts", "content": _generate_auth_token(auth)})
    output.append({"path": "shared/lib/auth/auth-provider.tsx", "content": _generate_auth_provider(auth)})
    output.append({"path": "shared/lib/auth/protected-route.tsx", "content": _generate_protected_route(auth)})
    output.append({"path": "shared/lib/auth/index.ts", "content": _generate_index()})

    # Callback route
    output.append({"path": "app/auth/callback/page.tsx", "content": _generate_callback_page()})
    output.append({"path": "app/auth/callback/callback-handler.tsx", "content": _generate_callback_handler(auth)})

    print(json.dumps(output))


if __name__ == "__main__":
    main()
