#!/usr/bin/env python3
"""
Generator: page-shells
Generates Next.js App Router routing shells from page components.
Input: YDK_COMPONENTS_PAGE
Output: src/app/{path}/page.tsx per page (thin 5-line shell)
"""

import json
import os
import re
import sys
from pathlib import Path

import yaml


def page_id_to_pascal(page_id: str) -> str:
    return "".join(p.capitalize() for p in re.split(r"[-_]", page_id) if p)


def path_to_app_dir(path: str) -> str:
    """Convert a page path like /resources/[id] to app router directory."""
    if path == "/":
        return ""
    # Remove leading slash
    return path.lstrip("/")


def _generate_detail_layout(page: dict) -> str:
    """Generate a layout.tsx for a detail page with sub-navigation."""
    page_id = _derive_page_id(page)
    title = page.get("title", page_id_to_pascal(page_id))
    children_pages = page.get("children", [])

    # Build sub-nav items
    nav_items = []
    for child in sorted(children_pages, key=lambda c: c.get("sub_nav_order", 99)):
        child_title = child.get("title", "")
        child_route = child.get("route", "")
        icon = child.get("sub_nav_icon", "Circle")
        nav_items.append(f'  {{ title: "{child_title}", href: "{child_route}", icon: "{icon}" }},')

    nav_items_str = "\n".join(nav_items)

    return f"""// Generated by YDK ignition
'use client';
import {{ usePathname }} from 'next/navigation';
import Link from 'next/link';
import {{ cn }} from '@/shared/lib/utils';

const SUB_NAV_ITEMS = [
{nav_items_str}
];

export default function {page_id_to_pascal(page_id)}Layout({{
  children,
}}: {{
  children: React.ReactNode;
}}) {{
  const pathname = usePathname();

  return (
    <div className="flex flex-col gap-6">
      <header className="border-b pb-4">
        <h1 className="text-2xl font-semibold">{title}</h1>
      </header>
      <div className="flex gap-6">
        <nav className="w-48 shrink-0 space-y-1">
          {{SUB_NAV_ITEMS.map((item) => (
            <Link
              key={{item.href}}
              href={{item.href}}
              className={{cn(
                'block rounded-md px-3 py-2 text-sm font-medium',
                pathname === item.href
                  ? 'bg-accent text-accent-foreground'
                  : 'text-muted-foreground hover:bg-muted'
              )}}
            >
              {{item.title}}
            </Link>
          ))}}
        </nav>
        <main className="flex-1 min-w-0">{{children}}</main>
      </div>
    </div>
  );
}}
"""


def _derive_page_id(page: dict) -> str:
    """Derive a page identifier from an YDK page component."""
    # Try 'id' field with YDK format: ydk:page:app/dashboard -> dashboard
    component_id = page.get("id", "")
    if component_id and "/" in component_id:
        return component_id.rsplit("/", 1)[1]
    if component_id and ":" in component_id:
        return component_id.split(":")[-1]
    return component_id or page.get("name", "")


def _process_page(page: dict, output: list) -> None:
    """Process a single page and its children."""
    page_id = _derive_page_id(page)
    path = page.get("route") or page.get("path", "/")
    title = page.get("title", page_id_to_pascal(page_id))
    children_pages = page.get("children", [])

    component_name = f"{page_id_to_pascal(page_id)}Page"
    import_path = f"@/_pages/{page_id}"
    app_dir = path_to_app_dir(path)
    output_path = f"{app_dir}/page.tsx" if app_dir else "page.tsx"

    # If this page has children, generate a layout and child page shells
    if children_pages:
        layout_content = _generate_detail_layout(page)
        layout_path = f"{app_dir}/layout.tsx" if app_dir else "layout.tsx"
        output.append({"path": layout_path, "content": layout_content})

        # Generate shells for child pages
        for child in children_pages:
            _process_page(child, output)
    else:
        content = "\n".join(
            [
                "// Generated by YDK ignition",
                "import type { Metadata } from 'next'",
                f"import {{ {component_name} }} from '{import_path}'",
                "",
                f"export const metadata: Metadata = {{ title: '{title}' }}",
                f"export default {component_name}",
                "",
            ]
        )
        output.append({"path": output_path, "content": content})


def main() -> None:
    pages_path = os.environ.get("YDK_COMPONENTS_PAGE", "")
    if not pages_path or not Path(pages_path).exists():
        print("Warning: YDK_COMPONENTS_PAGE not set or file missing — page-shells skipped.", file=sys.stderr)
        print(json.dumps([]))
        return

    # YDK passes a plain YAML list of page components
    pages = yaml.safe_load(Path(pages_path).read_text(encoding="utf-8")) or []
    if isinstance(pages, dict):
        pages = pages.get("pages", [])

    output = []
    for page in pages:
        _process_page(page, output)

    print(json.dumps(output))


if __name__ == "__main__":
    main()
