#!/usr/bin/env python3
"""
Generator: widget-stubs
Generates typed widget and feature stub components from page components or frontend-features.
Input: YDK_ARTIFACT_FRONTEND_FEATURES (preferred) | YDK_COMPONENTS_PAGE (fallback for widget inference)
       YDK_COMPONENTS_ENTITY (optional, for type hints)
Output:
  - src/widgets/{kebab-name}/index.tsx per widget
  - src/features/{kebab-name}/index.tsx per feature
"""

import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import yaml
from _context.naming import derive_name

TS_TYPE_MAP = {
    "str": "string",
    "string": "string",
    "int": "number",
    "integer": "number",
    "float": "number",
    "bool": "boolean",
    "boolean": "boolean",
    "uuid": "string",
    "datetime": "Date",
    "date": "Date",
    "json": "Record<string, unknown>",
}


def map_ts_type(t: str) -> str:
    t = t.strip()
    if t.startswith("optional[") and t.endswith("]"):
        return f"{map_ts_type(t[9:-1])} | undefined"
    if t.startswith("list[") and t.endswith("]"):
        return f"{map_ts_type(t[5:-1])}[]"
    return TS_TYPE_MAP.get(t, t)


def to_kebab(name: str) -> str:
    s1 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s1).lower()


def to_camel_lower(name: str) -> str:
    if not name:
        return name
    return name[0].lower() + name[1:]


def load_entity_fields(entity_name: str, entities: list[dict]) -> dict:
    """Load fields for a given entity from entity components (MAP format)."""
    for entity in entities:
        if derive_name(entity) == entity_name:
            return entity.get("fields", {})
    return {}


def generate_widget(widget: dict, entities: list[dict]) -> str:
    name = widget["name"]
    entity = widget.get("entity", "")
    explicit_props = widget.get("props", [])

    imports = set()
    prop_lines = []

    if entity and not explicit_props:
        # Auto-generate props from entity type
        imports.add(f"import type {{ {entity} }} from '@/shared/types/{to_camel_lower(entity)}'")
        prop_var = to_camel_lower(entity)
        prop_lines.append(f"  {prop_var}: {entity}")
        param_destructure = f"{{ {prop_var} }}: {name}Props"
    else:
        # Use explicit props
        for prop in explicit_props:
            prop_name = prop.get("name", "")
            prop_type = prop.get("type", "unknown")
            is_optional = prop.get("optional", False)
            default_val = prop.get("default", None)
            suffix = "?" if is_optional or default_val is not None else ""
            prop_lines.append(f"  {prop_name}{suffix}: {prop_type}")

        if explicit_props:
            first_props = [p.get("name", "") for p in explicit_props[:3]]
            param_destructure = "{ " + ", ".join(first_props) + ", ...props }: " + f"{name}Props"
        else:
            param_destructure = f"props: {name}Props"

    import_block = "\n".join(sorted(imports))
    props_block = "\n".join(prop_lines)
    props_interface = f"interface {name}Props {{\n{props_block}\n}}" if prop_lines else f"interface {name}Props {{}}"

    lines = ["// Generated by YDK ignition"]
    if import_block:
        lines += [import_block, ""]
    lines += [
        props_interface,
        "",
        f"// YDK-TODO: implement visual design for widget '{name}'",
        "// Props: "
        + (
            ", ".join(p.get("name", "") + ": " + p.get("type", entity) for p in explicit_props)
            if explicit_props
            else (to_camel_lower(entity) + ": " + entity if entity else "none")
        ),
        f"export function {name}({param_destructure}) {{",
        f"  throw new Error('{name} not implemented')",
        "}",
        "",
    ]
    return "\n".join(lines)


def generate_feature(feature: dict, entities: list[dict]) -> str:
    name = feature["name"]
    entity = feature.get("entity", "")
    feature_type = feature.get("type", "")
    mutation_hook = feature.get("mutation", "")
    fields = feature.get("fields", [])
    on_success = feature.get("on_success", "")

    imports = []
    if entity:
        imports.append(f"import type {{ {entity} }} from '@/shared/types/{to_camel_lower(entity)}'")
    if mutation_hook:
        # Derive the domain from hook name
        hook_without_use = mutation_hook[3:] if mutation_hook.startswith("use") else mutation_hook
        s1 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", hook_without_use)
        domain = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s1).lower()
        imports.append(f"import {{ {mutation_hook} }} from '@/shared/hooks/{domain}'")

    prop_lines = []
    if entity and feature_type in ("delete", "update"):
        prop_lines.append(f"  {to_camel_lower(entity)}: {entity}")
    if on_success:
        prop_lines.append("  onSuccess?: () => void")

    props_block = "\n".join(prop_lines)
    props_interface = f"interface {name}Props {{\n{props_block}\n}}" if prop_lines else f"interface {name}Props {{}}"

    param = (
        f"{{ {to_camel_lower(entity)}, onSuccess }}: {name}Props" if entity and prop_lines else f"props: {name}Props"
    )

    lines = ["// Generated by YDK ignition"]
    for imp in imports:
        lines.append(imp)
    lines += [
        "",
        props_interface,
        "",
        f"// YDK-TODO: implement {feature_type or 'interaction'} logic for '{name}'",
    ]
    if fields:
        lines.append(f"// Fields: {', '.join(fields)}")
    if mutation_hook:
        lines.append(f"// Mutation: {mutation_hook}")
    lines += [
        f"export function {name}({param}) {{",
    ]
    if mutation_hook:
        var_name = to_camel_lower(mutation_hook[3:]) if mutation_hook.startswith("use") else mutation_hook
        lines.append(f"  const {var_name} = {mutation_hook}()")
    lines += [
        f"  throw new Error('{name} not implemented')",
        "}",
        "",
    ]
    return "\n".join(lines)


def _load_features_data(env: dict) -> tuple[dict, list[dict]]:
    """Load artifact data and entity list. Returns (features_data, entities)."""
    # Load entities for type resolution
    entities: list[dict] = []
    entity_path = env.get("YDK_COMPONENTS_ENTITY", "")
    if entity_path and Path(entity_path).exists():
        raw_entities = yaml.safe_load(Path(entity_path).read_text(encoding="utf-8")) or []
        if isinstance(raw_entities, dict):
            raw_entities = raw_entities.get("entities", [])
        entities = raw_entities

    # New format: frontend-features artifact (id, title, queries, mutations, events)
    ff_path = env.get("YDK_ARTIFACT_FRONTEND_FEATURES", "")
    if ff_path and Path(ff_path).exists():
        raw = yaml.safe_load(Path(ff_path).read_text(encoding="utf-8")) or {}
        # Convert frontend_features list -> legacy {features: [...]} shape
        frontend_features = raw.get("frontend_features", [])
        converted_features = [
            {
                "name": "".join(w.capitalize() for w in f.get("id", "").replace("-", " ").split()),
                "entity": "",
                "type": "interaction",
                "mutation": f"useCreate{f.get('id', '').replace('-', '_').title().replace('_', '')}"
                if f.get("mutations")
                else "",
                "fields": [],
                "on_success": "",
            }
            for f in frontend_features
        ]
        return {"features": converted_features, "widgets": []}, entities

    return {}, entities


def main() -> None:
    data, entities = _load_features_data(dict(os.environ))
    if not data:
        print(json.dumps([]))
        return

    output = []

    for widget in data.get("widgets", []):
        name = widget.get("name", "")
        if not name:
            continue
        kebab = to_kebab(name)
        content = generate_widget(widget, entities)
        output.append({"path": f"widgets/{kebab}/index.tsx", "content": content})

    for feature in data.get("features", []):
        name = feature.get("name", "")
        if not name:
            continue
        kebab = to_kebab(name)
        content = generate_feature(feature, entities)
        output.append({"path": f"features/{kebab}/index.tsx", "content": content})

    print(json.dumps(output))


if __name__ == "__main__":
    main()
