"""Canonical type mappings for YDK generators (YDK canonical type system)."""

from __future__ import annotations

# YDK canonical type string → Python type annotation string
CANONICAL_TO_PYTHON: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "bigint": "int",
    "float": "float",
    "boolean": "bool",
    "UUID": "UUID",
    "Decimal": "Decimal",
    "datetime": "datetime",
    "date": "date",
    "text": "str",
    "json": "dict[str, Any]",
    "enum": "str",
    "bytes": "bytes",
    # Legacy aliases (for backward compatibility)
    "str": "str",
    "int": "int",
    "bool": "bool",
    "uuid": "UUID",
    # Optional wrappers
    "optional[string]": "str | None",
    "optional[integer]": "int | None",
    "optional[int]": "int | None",
    "optional[float]": "float | None",
    "optional[boolean]": "bool | None",
    "optional[bool]": "bool | None",
    "optional[UUID]": "UUID | None",
    "optional[uuid]": "UUID | None",
    "optional[Decimal]": "Decimal | None",
    "optional[datetime]": "datetime | None",
    "optional[date]": "date | None",
    "optional[text]": "str | None",
    "optional[json]": "dict[str, Any] | None",
    "optional[str]": "str | None",
    "optional[bytes]": "bytes | None",
    # Collection types
    "list[str]": "list[str]",
    "list[string]": "list[str]",
    "list[int]": "list[int]",
    "list[integer]": "list[int]",
    "optional[list[str]]": "list[str] | None",
    "optional[list[string]]": "list[str] | None",
    "any": "Any",
}

# YDK canonical type → (SQLAlchemy type class name, constructor args list)
CANONICAL_TO_SQLALCHEMY: dict[str, tuple[str, list[str]]] = {
    "string": ("String", []),
    "integer": ("Integer", []),
    "bigint": ("BigInteger", []),
    "float": ("Numeric", ["precision=18", "scale=6"]),
    "boolean": ("Boolean", []),
    "UUID": ("UUID", ["as_uuid=True"]),
    "Decimal": ("Numeric", ["precision=18", "scale=6"]),
    "decimal": ("Numeric", ["precision=18", "scale=6"]),
    "datetime": ("DateTime", ["timezone=True"]),
    "date": ("Date", []),
    "text": ("Text", []),
    "json": ("JSONB", []),
    "enum": ("String", []),
    "bytes": ("LargeBinary", []),
    # Legacy aliases
    "str": ("String", []),
    "int": ("Integer", []),
    "bool": ("Boolean", []),
    "uuid": ("UUID", ["as_uuid=True"]),
    # Optional variants (same SA type, nullability handled by column def)
    "optional[string]": ("String", []),
    "optional[str]": ("String", []),
    "optional[integer]": ("Integer", []),
    "optional[int]": ("Integer", []),
    "optional[float]": ("Numeric", ["precision=18", "scale=6"]),
    "optional[boolean]": ("Boolean", []),
    "optional[bool]": ("Boolean", []),
    "optional[UUID]": ("UUID", ["as_uuid=True"]),
    "optional[uuid]": ("UUID", ["as_uuid=True"]),
    "optional[decimal]": ("Numeric", ["precision=18", "scale=6"]),
    "optional[Decimal]": ("Numeric", ["precision=18", "scale=6"]),
    "optional[datetime]": ("DateTime", ["timezone=True"]),
    "optional[date]": ("Date", []),
    "optional[text]": ("Text", []),
    "optional[json]": ("JSONB", []),
    "optional[bytes]": ("LargeBinary", []),
    "list[str]": ("ARRAY", ["String()"]),
    "list[string]": ("ARRAY", ["String()"]),
    "list[int]": ("ARRAY", ["Integer()"]),
    "list[integer]": ("ARRAY", ["Integer()"]),
    "optional[list[str]]": ("JSONB", []),
    "optional[list[string]]": ("JSONB", []),
}

# YDK canonical type → Pydantic-friendly Python type string
CANONICAL_TO_PYDANTIC: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "bigint": "int",
    "float": "float",
    "boolean": "bool",
    "UUID": "UUID",
    "Decimal": "Decimal",
    "datetime": "datetime",
    "date": "date",
    "text": "str",
    "json": "dict[str, Any]",
    "enum": "str",
    "bytes": "bytes",
    "decimal": "Decimal",
    "object": "dict[str, Any]",
    "jsonb": "dict[str, Any]",
    # Legacy aliases
    "str": "str",
    "int": "int",
    "bool": "bool",
    "uuid": "UUID",
    # Optional variants
    "optional[string]": "str | None",
    "optional[str]": "str | None",
    "optional[integer]": "int | None",
    "optional[int]": "int | None",
    "optional[float]": "float | None",
    "optional[boolean]": "bool | None",
    "optional[bool]": "bool | None",
    "optional[UUID]": "UUID | None",
    "optional[uuid]": "UUID | None",
    "optional[Decimal]": "Decimal | None",
    "optional[decimal]": "Decimal | None",
    "optional[datetime]": "datetime | None",
    "optional[date]": "date | None",
    "optional[text]": "str | None",
    "optional[json]": "dict[str, Any] | None",
    "optional[object]": "dict[str, Any] | None",
    "optional[jsonb]": "dict[str, Any] | None",
    "optional[bytes]": "bytes | None",
    "list[str]": "list[str]",
    "list[string]": "list[str]",
    "list[int]": "list[int]",
    "list[integer]": "list[int]",
    "optional[list[str]]": "list[str] | None",
    "optional[list[string]]": "list[str] | None",
    "any": "Any",
}

# Canonical types that are nullable (Optional[...])
NULLABLE_TYPES: frozenset[str] = frozenset(t for t in CANONICAL_TO_PYTHON if t.startswith("optional["))

# Canonical types that need stdlib imports
STDLIB_IMPORTS: dict[str, str] = {
    "UUID": "from uuid import UUID",
    "uuid": "from uuid import UUID",
    "optional[UUID]": "from uuid import UUID",
    "optional[uuid]": "from uuid import UUID",
    "Decimal": "from decimal import Decimal",
    "decimal": "from decimal import Decimal",
    "optional[Decimal]": "from decimal import Decimal",
    "optional[decimal]": "from decimal import Decimal",
    "datetime": "from datetime import datetime",
    "optional[datetime]": "from datetime import datetime",
    "date": "from datetime import date",
    "optional[date]": "from datetime import date",
    "json": "from typing import Any",
    "optional[json]": "from typing import Any",
    "any": "from typing import Any",
}

# SQLAlchemy type class → import source
SQLALCHEMY_IMPORTS: dict[str, str] = {
    "String": "from sqlalchemy import String",
    "Integer": "from sqlalchemy import Integer",
    "BigInteger": "from sqlalchemy import BigInteger",
    "Float": "from sqlalchemy import Float",
    "Numeric": "from sqlalchemy import Numeric",
    "Boolean": "from sqlalchemy import Boolean",
    "UUID": "from sqlalchemy.dialects.postgresql import UUID",
    "DateTime": "from sqlalchemy import DateTime",
    "Date": "from sqlalchemy import Date",
    "Text": "from sqlalchemy import Text",
    "LargeBinary": "from sqlalchemy import LargeBinary",
    "JSONB": "from sqlalchemy.dialects.postgresql import JSONB",
    "ARRAY": "from sqlalchemy.dialects.postgresql import ARRAY",
}
