#!/usr/bin/env python3
"""
Generator: endpoint-test-stubs
Generates xUnit integration test stubs per route tag, exercising the Minimal
API endpoints generated by api_endpoints.py (task #106) through
WebApplicationFactory<Program> (Program.cs declares `public partial class
Program {}` -- see templates/api/program.cs.j2 -- specifically to support
this ASP.NET Core testing convention; Microsoft.AspNetCore.Mvc.Testing is
already referenced by templates/solution/tests.csproj.j2, task #103).

Route grouping mirrors api_endpoints.py exactly (same route_tag/
tag_class_prefix helpers, reused directly rather than duplicated) so each
{Tag}EndpointsTests.cs exercises the matching {Tag}Endpoints.cs.

Since Program.cs does not yet wire AddApplicationServices()/Map{Tag}Endpoints()
calls (left for a later task) and the backing services still throw
NotImplementedException (task #105), each test only asserts that a response
comes back -- a TODO comment marks where real status/body assertions belong
once wiring + implementation land.

Input: YDK route components
Output: {Solution}.Tests/Endpoints/{Tag}EndpointsTests.cs per route tag
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

# Add generators dir to path for local helper imports
sys.path.insert(0, str(Path(__file__).parent))

import yaml
from _dotnet_common import to_pascal
from api_endpoints import route_tag, tag_class_prefix
from jinja2 import Environment, FileSystemLoader, StrictUndefined

TESTS_DIR = "WebApiClean.Tests"

_PATH_PARAM_RE = re.compile(r"\{(\w+)(:[^}]*)?\}")
_HTTP_METHOD_CALL = {
    "GET": "GetAsync",
    "POST": "PostAsync",
    "PUT": "PutAsync",
    "PATCH": "PatchAsync",
    "DELETE": "DeleteAsync",
}
_BODY_METHODS = frozenset({"POST", "PUT", "PATCH"})


def _sample_path(path: str) -> str:
    """Replace every `{param}` path segment with a generic sample value."""
    return _PATH_PARAM_RE.sub("1", path)


def _case_name(method: str, path: str) -> str:
    segments = [s for s in path.strip("/").split("/") if s]
    slug = "_".join(segments) if segments else "root"
    return to_pascal(f"{method}_{slug}")


def build_tag_context(tag: str, routes: list[dict]) -> dict:
    """Build the Jinja2 template context for one {Tag}EndpointsTests.cs file."""
    cases = []
    for ep in routes:
        method = str(ep.get("method", "GET")).upper()
        path = _sample_path(str(ep.get("path", "/")))
        cases.append(
            {
                "name": _case_name(method, path),
                "call": _HTTP_METHOD_CALL.get(method, "GetAsync"),
                "path": path,
                "has_body": method in _BODY_METHODS,
            }
        )
    return {"tag": tag_class_prefix(tag), "cases": cases}


def main() -> None:
    route_path = os.environ.get("YDK_COMPONENTS_ROUTE", "")
    if not route_path or not Path(route_path).exists():
        print("Error: YDK_COMPONENTS_ROUTE not set or file not found", file=sys.stderr)
        sys.exit(1)

    data = yaml.safe_load(Path(route_path).read_text(encoding="utf-8"))
    routes = data if isinstance(data, list) else []

    # Group by PascalCase tag, same as api_endpoints.py, so tag files line up 1:1.
    groups: dict[str, list[dict]] = {}
    for ep in routes:
        groups.setdefault(tag_class_prefix(route_tag(ep)), []).append(ep)

    templates_dir = Path(__file__).parent.parent / "templates" / "tests"
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    template = env.get_template("endpoint_test.cs.j2")

    output = []
    for tag in sorted(groups):
        context = build_tag_context(tag, groups[tag])
        content = template.render(**context).rstrip() + "\n"
        output.append({"path": f"{TESTS_DIR}/Endpoints/{context['tag']}EndpointsTests.cs", "content": content})

    print(json.dumps(output))


if __name__ == "__main__":
    main()
