"""Tests for the ydk-pr-body.yml CI template and its registration."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import yaml

from ydk.core import ci_generator
from ydk.core.ci_generator import CiContext, generate_ci, render

if TYPE_CHECKING:
    from pathlib import Path

CTX = CiContext(
    version="1.5.0",
    stack="python-cli",
    spec_location="docs/specs",
    components_path=".ydk/components",
    schemas_path=".ydk/schemas",
)


def _rendered() -> str:
    return render((ci_generator.TEMPLATES_DIR / "ydk-pr-body.yml").read_text(encoding="utf-8"), CTX)


def _parsed() -> dict[Any, Any]:
    return yaml.safe_load(_rendered())


def _triggers(doc: dict[Any, Any]) -> dict[str, Any]:
    # PyYAML parses the bare key `on` as boolean True.
    return doc.get("on", doc.get(True))


def test_registered_target() -> None:
    match = [t for t in ci_generator.CI_TARGETS if t.output == "ydk-pr-body.yml"]
    assert len(match) == 1
    assert match[0].template == "ydk-pr-body.yml"
    assert match[0].condition(CTX) is True


def test_header_and_version_pin() -> None:
    text = _rendered()
    assert text.startswith("# Generated by ydk ci init v1.5.0. Re-run 'ydk ci init --force' to regenerate.\n")
    assert 'YDK_VERSION: "1.5.0"' in text
    assert "{{" not in text.replace("${{", "")


def test_trigger_and_permissions() -> None:
    doc = _parsed()
    assert _triggers(doc)["pull_request"]["types"] == ["opened", "edited", "synchronize", "reopened"]
    assert doc["permissions"] == {"contents": "read"}


def test_concurrency() -> None:
    conc = _parsed()["concurrency"]
    assert conc["group"] == "${{ github.workflow }}-${{ github.ref }}"
    assert conc["cancel-in-progress"] == "${{ github.event_name == 'pull_request' }}"


def test_pr_body_job_steps() -> None:
    steps = _parsed()["jobs"]["pr-body"]["steps"]
    checkout = next(s for s in steps if str(s.get("uses", "")).startswith("actions/checkout"))
    assert checkout["with"]["fetch-depth"] == 0
    assert any(str(s.get("uses", "")).startswith("astral-sh/setup-uv@") for s in steps)
    runs = "\n".join(s["run"] for s in steps if "run" in s)
    assert 'uv tool install --python 3.13 "git+https://github.com/yoavarad/ydk@v${YDK_VERSION}"' in runs
    assert 'ydk verify pr-body --body-file "$RUNNER_TEMP/pr-body.md" --base-ref "origin/$BASE_REF"' in runs


def test_body_passed_via_env_not_interpolated() -> None:
    steps = _parsed()["jobs"]["pr-body"]["steps"]
    check = next(s for s in steps if "pr-body.md" in s.get("run", ""))
    assert check["env"]["PR_BODY"] == "${{ github.event.pull_request.body }}"
    assert check["env"]["BASE_REF"] == "${{ github.event.pull_request.base.ref }}"
    assert "printf '%s' \"$PR_BODY\"" in check["run"]
    assert "${{" not in check["run"]


def test_generate_ci_writes_workflow(tmp_path: Path) -> None:
    (tmp_path / ".ydk").mkdir()
    (tmp_path / ".ydk" / "config.yaml").write_text(
        "project:\n  name: demo\n  remote: github\n  stack: python-cli\n  spec_location: docs/specs\n"
        "components:\n  components_path: .ydk/components\n  schemas_path: .ydk/schemas\n",
        encoding="utf-8",
    )
    result = generate_ci(tmp_path, force=False, version="1.5.0")
    assert ".github/workflows/ydk-pr-body.yml" in result.written
    assert (tmp_path / ".github" / "workflows" / "ydk-pr-body.yml").is_file()
