"""Tests for the CI workflow generator engine."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
import yaml

from ydk.core import ci_generator
from ydk.core.ci_generator import (
    PR_TEMPLATE,
    CiConfigError,
    CiContext,
    CiTarget,
    generate_ci,
    is_release_version,
    render,
    select_stack_target,
)

if TYPE_CHECKING:
    from pathlib import Path


def _write_config(root: Path, remote: str = "github", stack: str = "python-cli") -> None:
    (root / ".ydk").mkdir(parents=True, exist_ok=True)
    (root / ".ydk" / "config.yaml").write_text(
        f"project:\n  name: demo\n  remote: {remote}\n  stack: {stack}\n  spec_location: docs/specs\n"
        "components:\n  components_path: .ydk/components\n  schemas_path: .ydk/schemas\n",
        encoding="utf-8",
    )


def _templates(tmp_path: Path) -> Path:
    tdir = tmp_path / "tpl"
    tdir.mkdir()
    (tdir / "demo.yml").write_text(
        "name: demo\n# ydk {{YDK_VERSION}} stack={{STACK}} spec={{SPEC_LOCATION}}\n"
        "# comp={{COMPONENTS_PATH}} schemas={{SCHEMAS_PATH}}\n"
        "group: ${{ github.workflow }}\n",
        encoding="utf-8",
    )
    return tdir


DEMO = CiTarget(template="demo.yml", output="demo.yml", purpose="Demo workflow")
NEVER = CiTarget(template="demo.yml", output="never.yml", purpose="Never", condition=lambda ctx: False)


def _ctx(version: str = "1.5.0") -> CiContext:
    return CiContext(
        version=version,
        stack="python-cli",
        spec_location="docs/specs",
        components_path=".ydk/components",
        schemas_path=".ydk/schemas",
    )


def test_registry_lists_pr_checks() -> None:
    assert "ydk-pr-checks.yml" in [t.output for t in ci_generator.CI_TARGETS]


def test_templates_dir_is_package_data() -> None:
    assert ci_generator.TEMPLATES_DIR.is_dir()


def test_render_header_and_placeholders() -> None:
    out = render("x: {{YDK_VERSION}}\ns: {{STACK}}\ng: ${{ github.ref }}\n", _ctx())
    assert out.startswith("# Generated by ydk ci init v1.5.0. Re-run 'ydk ci init --force' to regenerate.\n")
    assert "x: 1.5.0" in out
    assert "s: python-cli" in out
    assert "g: ${{ github.ref }}" in out


def test_render_is_deterministic() -> None:
    assert render("a {{YDK_VERSION}}", _ctx()) == render("a {{YDK_VERSION}}", _ctx())


@pytest.mark.parametrize(
    ("version", "expected"),
    [("1.5.0", True), ("1.5.0.dev3", False), ("1.5.0+local", False), ("1.5.0.dev3+g1234", False)],
)
def test_is_release_version(version: str, expected: bool) -> None:
    assert is_release_version(version) is expected


def test_missing_config_raises_and_writes_nothing(tmp_path: Path) -> None:
    with pytest.raises(CiConfigError, match="config"):
        generate_ci(tmp_path, force=False, version="1.5.0")
    assert not (tmp_path / ".github").exists()


def test_non_github_remote_raises_and_writes_nothing(tmp_path: Path) -> None:
    _write_config(tmp_path, remote="local")
    with pytest.raises(CiConfigError, match="github"):
        generate_ci(tmp_path, force=False, version="1.5.0")
    assert not (tmp_path / ".github").exists()


def test_fresh_writes_targets_and_pr_template(tmp_path: Path) -> None:
    _write_config(tmp_path)
    result = generate_ci(
        tmp_path, force=False, version="1.5.0", targets=[DEMO, NEVER], templates_dir=_templates(tmp_path)
    )
    wf = tmp_path / ".github" / "workflows" / "demo.yml"
    assert wf.read_text(encoding="utf-8").startswith("# Generated by ydk ci init v1.5.0.")
    body = wf.read_text(encoding="utf-8")
    assert "stack=python-cli spec=docs/specs" in body
    assert "comp=.ydk/components schemas=.ydk/schemas" in body
    assert not (tmp_path / ".github" / "workflows" / "never.yml").exists()
    pr = tmp_path / ".github" / "PULL_REQUEST_TEMPLATE.md"
    assert pr.read_text(encoding="utf-8") == PR_TEMPLATE
    assert [(f.path, f.action) for f in result.files] == [
        (".github/workflows/demo.yml", "written"),
        (".github/PULL_REQUEST_TEMPLATE.md", "written"),
    ]
    assert result.files[0].purpose == "Demo workflow"
    assert result.written == [".github/workflows/demo.yml", ".github/PULL_REQUEST_TEMPLATE.md"]
    assert result.skipped == []
    assert result.unpublished is False


def test_second_run_skips_and_leaves_files_untouched(tmp_path: Path) -> None:
    _write_config(tmp_path)
    tdir = _templates(tmp_path)
    generate_ci(tmp_path, force=False, version="1.5.0", targets=[DEMO], templates_dir=tdir)
    wf = tmp_path / ".github" / "workflows" / "demo.yml"
    pr = tmp_path / ".github" / "PULL_REQUEST_TEMPLATE.md"
    wf.write_text("custom", encoding="utf-8")
    before = {p: (p.read_bytes(), p.stat().st_mtime_ns) for p in (wf, pr)}
    result = generate_ci(tmp_path, force=False, version="1.6.0", targets=[DEMO], templates_dir=tdir)
    assert {p: (p.read_bytes(), p.stat().st_mtime_ns) for p in (wf, pr)} == before
    assert [f.action for f in result.files] == ["skipped (exists)", "skipped (exists)"]
    assert result.written == []
    assert result.skipped == [".github/workflows/demo.yml", ".github/PULL_REQUEST_TEMPLATE.md"]


def test_force_overwrites_targets_only(tmp_path: Path) -> None:
    _write_config(tmp_path)
    tdir = _templates(tmp_path)
    generate_ci(tmp_path, force=False, version="1.5.0", targets=[DEMO], templates_dir=tdir)
    wf = tmp_path / ".github" / "workflows" / "demo.yml"
    pr = tmp_path / ".github" / "PULL_REQUEST_TEMPLATE.md"
    other = tmp_path / ".github" / "workflows" / "mine.yml"
    other.write_text("mine", encoding="utf-8")
    wf.write_text("custom", encoding="utf-8")
    pr.write_text("custom pr", encoding="utf-8")
    other_mtime = other.stat().st_mtime_ns
    result = generate_ci(tmp_path, force=True, version="1.6.0", targets=[DEMO], templates_dir=tdir)
    assert wf.read_text(encoding="utf-8").startswith("# Generated by ydk ci init v1.6.0.")
    assert pr.read_text(encoding="utf-8") == PR_TEMPLATE
    assert other.read_text(encoding="utf-8") == "mine"
    assert other.stat().st_mtime_ns == other_mtime
    assert [f.action for f in result.files] == ["overwritten", "overwritten"]
    assert result.written == [".github/workflows/demo.yml", ".github/PULL_REQUEST_TEMPLATE.md"]


PYTHON_STACKS = ["python-fastapi", "python-cli"]


def _load_workflow(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


@pytest.mark.parametrize("stack", PYTHON_STACKS)
def test_select_stack_target_python(stack: str) -> None:
    target = select_stack_target(stack)
    assert target is not None
    assert (target.template, target.output, target.purpose) == ("ci-python.yml", "ci.yml", "stack CI (python)")


@pytest.mark.parametrize("stack", ["", "dotnet", "nextjs-fsd", "terraform", "unknown"])
def test_select_stack_target_other_stacks_have_none_yet(stack: str) -> None:
    assert select_stack_target(stack) is None


@pytest.mark.parametrize("stack", PYTHON_STACKS)
def test_python_stack_writes_ci_yml(tmp_path: Path, stack: str) -> None:
    _write_config(tmp_path, stack=stack)
    (tmp_path / "uv.lock").write_text("", encoding="utf-8")
    result = generate_ci(tmp_path, force=False, version="1.5.0")
    ci = tmp_path / ".github" / "workflows" / "ci.yml"
    text = ci.read_text(encoding="utf-8")
    assert text.startswith("# Generated by ydk ci init v1.5.0.")
    assert "ydk" not in text.split("\n", 1)[1]  # nothing YDK-specific below the header
    wf = _load_workflow(ci)
    triggers = wf[True]  # YAML 1.1 parses the `on` key as boolean True
    assert "pull_request" in triggers
    assert "workflow_dispatch" in triggers
    assert triggers["push"]["branches"] == ["main"]
    assert wf["permissions"] == {"contents": "read"}
    assert wf["concurrency"] == {
        "group": "${{ github.workflow }}-${{ github.ref }}",
        "cancel-in-progress": "${{ github.event_name == 'pull_request' }}",
    }
    assert set(wf["jobs"]) == {"lint", "test"}
    for job in wf["jobs"].values():
        steps = job["steps"]
        assert steps[0]["uses"] == "actions/checkout@v4"
        assert steps[1] == {"uses": "astral-sh/setup-uv@v7", "with": {"enable-cache": True}}
        assert steps[2]["run"] == "uv sync --locked --all-extras --dev"
    lint_runs = [s["run"] for s in wf["jobs"]["lint"]["steps"][3:]]
    assert lint_runs == ["uv run ruff check .", "uv run ruff format --check .", "uv run ty check"]
    test_runs = [s["run"] for s in wf["jobs"]["test"]["steps"][3:]]
    assert test_runs == ["uv run pytest -q --tb=short"]
    ci_row = next(f for f in result.files if f.path == ".github/workflows/ci.yml")
    assert (ci_row.action, ci_row.purpose) == ("written", "stack CI (python)")
    assert result.warnings == []


def test_python_stack_missing_uv_lock_warns_and_still_writes(tmp_path: Path) -> None:
    _write_config(tmp_path, stack="python-cli")
    result = generate_ci(tmp_path, force=False, version="1.5.0")
    assert (tmp_path / ".github" / "workflows" / "ci.yml").is_file()
    assert len(result.warnings) == 1
    assert "uv.lock" in result.warnings[0]


@pytest.mark.parametrize("stack", ["", "dotnet", "terraform"])
def test_non_python_stack_writes_no_ci_yml_and_no_warning(tmp_path: Path, stack: str) -> None:
    _write_config(tmp_path, stack=stack or '""')
    result = generate_ci(tmp_path, force=False, version="1.5.0")
    assert not (tmp_path / ".github" / "workflows" / "ci.yml").exists()
    assert result.warnings == []


def test_existing_ci_yml_skipped_then_forced(tmp_path: Path) -> None:
    _write_config(tmp_path, stack="python-fastapi")
    (tmp_path / "uv.lock").write_text("", encoding="utf-8")
    ci = tmp_path / ".github" / "workflows" / "ci.yml"
    ci.parent.mkdir(parents=True)
    ci.write_text("hand-written", encoding="utf-8")
    result = generate_ci(tmp_path, force=False, version="1.5.0")
    assert ci.read_text(encoding="utf-8") == "hand-written"
    assert ".github/workflows/ci.yml" in result.skipped
    forced = generate_ci(tmp_path, force=True, version="1.5.0")
    assert ci.read_text(encoding="utf-8").startswith("# Generated by ydk ci init v1.5.0.")
    assert ".github/workflows/ci.yml" in forced.written
    assert next(f for f in forced.files if f.path == ".github/workflows/ci.yml").action == "overwritten"


def test_version_defaults_to_installed_metadata(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    _write_config(tmp_path)
    monkeypatch.setattr(ci_generator.importlib.metadata, "version", lambda name: "1.5.0.dev3")
    result = generate_ci(tmp_path, force=False, targets=[DEMO], templates_dir=_templates(tmp_path))
    assert result.version == "1.5.0.dev3"
    assert result.unpublished is True
    text = (tmp_path / ".github" / "workflows" / "demo.yml").read_text(encoding="utf-8")
    assert "# ydk 1.5.0.dev3" in text
