"""Tests for the ydk-delete-merged-branch.yml CI template."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import yaml

from ydk.core.ci_generator import CI_TARGETS, generate_ci

if TYPE_CHECKING:
    from pathlib import Path

    from ydk.core.ci_generator import CiTarget

OUTPUT = "ydk-delete-merged-branch.yml"


def _target() -> CiTarget:
    return next(t for t in CI_TARGETS if t.output == OUTPUT)


def _rendered(tmp_path: Path) -> tuple[str, dict[str, Any]]:
    (tmp_path / ".ydk").mkdir()
    (tmp_path / ".ydk" / "config.yaml").write_text(
        "project:\n  name: demo\n  remote: github\n  stack: python-cli\n", encoding="utf-8"
    )
    generate_ci(tmp_path, force=False, version="1.5.0", targets=[_target()])
    text = (tmp_path / ".github" / "workflows" / OUTPUT).read_text(encoding="utf-8")
    return text, yaml.safe_load(text)


def test_registered_unconditionally() -> None:
    t = _target()
    assert t.template == OUTPUT
    assert t.purpose


def test_header_and_yaml_parses(tmp_path: Path) -> None:
    text, data = _rendered(tmp_path)
    assert text.startswith("# Generated by ydk ci init v1.5.0. Re-run 'ydk ci init --force' to regenerate.\n")
    assert isinstance(data, dict)


def test_trigger_and_permissions(tmp_path: Path) -> None:
    _, data = _rendered(tmp_path)
    assert data[True] == {"pull_request": {"types": ["closed"]}}  # PyYAML parses `on` as True
    assert data["permissions"] == {"contents": "write"}
    assert "concurrency" not in data


def test_guard_merged_same_repo_not_default(tmp_path: Path) -> None:
    _, data = _rendered(tmp_path)
    cond = data["jobs"]["delete-branch"]["if"]
    assert "github.event.pull_request.merged == true" in cond
    assert "head.repo.full_name == github.repository" in cond
    assert "head.ref != github.event.repository.default_branch" in cond


def test_delete_step_tolerant_and_env_safe(tmp_path: Path) -> None:
    text, data = _rendered(tmp_path)
    step = data["jobs"]["delete-branch"]["steps"][0]
    assert step["env"]["BRANCH"] == "${{ github.event.pull_request.head.ref }}"
    assert "gh api -X DELETE" in step["run"]
    assert "git/refs/heads/${BRANCH}" in step["run"]
    assert "already gone or protected" in step["run"]
    assert "run: ${{ github.event.pull_request.head.ref" not in text
    assert "ydk" not in step["run"]
