"""Tests for the ydk-sync.yml CI template and its registration."""

from __future__ import annotations

import yaml

from ydk.core import ci_generator
from ydk.core.ci_generator import CiContext, render

CTX = CiContext(
    version="1.5.0",
    stack="python-cli",
    spec_location="docs/specs",
    components_path=".ydk/components",
    schemas_path=".ydk/schemas",
)


def _text() -> str:
    return render((ci_generator.TEMPLATES_DIR / "ydk-sync.yml").read_text(encoding="utf-8"), CTX)


def _workflow() -> dict:
    return yaml.safe_load(_text())


def test_registered_always() -> None:
    match = [t for t in ci_generator.CI_TARGETS if t.output == "ydk-sync.yml"]
    assert len(match) == 1
    assert match[0].template == "ydk-sync.yml"
    assert match[0].condition(CTX) is True


def test_triggers() -> None:
    wf = _workflow()
    triggers = wf.get("on") or wf[True]
    assert "workflow_dispatch" in triggers
    assert set(triggers) == {"push", "workflow_dispatch"}
    assert "github.event.repository.default_branch" in wf["jobs"]["sync"]["if"]


def test_permissions_and_concurrency() -> None:
    wf = _workflow()
    assert wf["permissions"] == {"contents": "read", "issues": "write", "pull-requests": "read"}
    assert wf["concurrency"] == {"group": "ydk-sync", "cancel-in-progress": False}


def test_env_and_header() -> None:
    text = _text()
    assert text.startswith("# Generated by ydk ci init")
    assert _workflow()["env"] == {"YDK_VERSION": "1.5.0"}


def test_sync_job_steps_in_order() -> None:
    job = _workflow()["jobs"]["sync"]
    assert job["env"]["GH_TOKEN"] == "${{ secrets.GITHUB_TOKEN }}"
    assert job["env"]["GH_REPO"] == "${{ github.repository }}"
    steps = job["steps"]
    assert steps[0]["uses"] == "actions/checkout@v4"
    assert steps[1]["uses"] == "astral-sh/setup-uv@v7"
    runs = [s["run"] for s in steps if "run" in s]
    assert runs[0] == 'uv tool install --python 3.13 "git+https://github.com/yoavarad/ydk@v${YDK_VERSION}"'
    assert runs[1:] == ["ydk task sync", "ydk task sync-issues"]
