#!/usr/bin/env python3
"""
Generator: msw-handlers
Generates MSW (Mock Service Worker) request handlers from openapi.json.

Input: ODK_ARTIFACT_OPENAPI
Output: src/shared/test/mocks/handlers.ts, server.ts, browser.ts

Deferred-safe: prints [] and exits 0 when artifact is missing.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))


def _generate_mock_response(schema: dict, schemas: dict, depth: int = 0) -> str:
    """Generate a mock response value from an OpenAPI schema."""
    if depth > 3:
        return "{}"

    if "$ref" in schema:
        ref_name = schema["$ref"].split("/")[-1]
        if ref_name in schemas:
            return _generate_mock_response(schemas[ref_name], schemas, depth + 1)
        return "{}"

    schema_type = schema.get("type", "object")

    if schema_type == "array":
        items = schema.get("items", {})
        item_mock = _generate_mock_response(items, schemas, depth + 1)
        return f"[{item_mock}]"

    if schema_type == "object":
        props = schema.get("properties", {})
        if not props:
            return "{}"
        fields = []
        for name, prop in props.items():
            value = _mock_value_for_property(name, prop, schemas, depth)
            fields.append(f"      {name}: {value}")
        return "{\n" + ",\n".join(fields) + "\n    }"

    return _mock_primitive(schema_type, schema)


def _mock_value_for_property(name: str, prop: dict, schemas: dict, depth: int) -> str:
    """Generate a mock value for a single property."""
    if "$ref" in prop:
        return _generate_mock_response(prop, schemas, depth + 1)

    prop_type = prop.get("type", "string")

    if prop_type == "array":
        return "[]"
    if prop_type == "object":
        return "{}"

    return _mock_primitive(prop_type, prop)


def _mock_primitive(type_str: str, prop: dict) -> str:
    """Generate a primitive mock value."""
    if "enum" in prop:
        return f"'{prop['enum'][0]}'"

    fmt = prop.get("format", "")

    if type_str == "string":
        if fmt == "date-time":
            return "'2024-01-01T00:00:00Z'"
        if fmt == "date":
            return "'2024-01-01'"
        if fmt == "uuid":
            return "'00000000-0000-0000-0000-000000000001'"
        return "'mock-value'"
    if type_str == "integer" or type_str == "number":
        return "1"
    if type_str == "boolean":
        return "true"
    return "'mock-value'"


def _method_to_msw(method: str) -> str:
    """Convert HTTP method to MSW http method."""
    return method.lower()


def _openapi_path_to_msw(path: str) -> str:
    """Convert OpenAPI path params {id} to MSW :id syntax."""
    import re

    return re.sub(r"\{([^}]+)\}", r":\1", path)


def main() -> None:
    openapi_path = os.environ.get("ODK_ARTIFACT_OPENAPI", "")
    if not openapi_path or not Path(openapi_path).exists():
        print(
            "Warning: ODK_ARTIFACT_OPENAPI not set or file missing — msw-handlers deferred.",
            file=sys.stderr,
        )
        print(json.dumps([]))
        return

    spec = json.loads(Path(openapi_path).read_text(encoding="utf-8"))
    paths = spec.get("paths", {})
    schemas = spec.get("components", {}).get("schemas", {})

    handlers_lines = [
        "// Generated by ODK ignition",
        "// MSW request handlers derived from openapi.json",
        "",
        "import { http, HttpResponse } from 'msw';",
        "",
        "const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000';",
        "",
        "export const handlers = [",
    ]

    for path, path_item in paths.items():
        for method, operation in path_item.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue

            msw_path = _openapi_path_to_msw(path)
            msw_method = _method_to_msw(method)
            op_id = operation.get("operationId", f"{method}_{path}")

            # Determine response
            responses = operation.get("responses", {})
            success_code = None
            response_schema = None

            for code in ["200", "201", "204"]:
                if code in responses:
                    success_code = code
                    content = responses[code].get("content", {})
                    if "application/json" in content:
                        response_schema = content["application/json"].get("schema", {})
                    break

            if success_code == "204":
                body = "return new HttpResponse(null, { status: 204 });"
                handler = f"  // {op_id}\n  http.{msw_method}(`${{BASE_URL}}{msw_path}`, () => {{\n    {body}\n  }}),"
            elif response_schema:
                mock = _generate_mock_response(response_schema, schemas)
                handler = (
                    f"  // {op_id}\n"
                    f"  http.{msw_method}(`${{BASE_URL}}{msw_path}`, () => {{\n"
                    f"    return HttpResponse.json({mock});\n  }}),"
                )
            else:
                handler = (
                    f"  // {op_id}\n"
                    f"  http.{msw_method}(`${{BASE_URL}}{msw_path}`, () => {{\n"
                    f"    return HttpResponse.json({{}});\n  }}),"
                )

            handlers_lines.append(handler)
            handlers_lines.append("")

    handlers_lines.append("];")
    handlers_lines.append("")

    handlers_content = "\n".join(handlers_lines)

    server_content = """// Generated by ODK ignition
// MSW server for Node.js test environment
import { setupServer } from 'msw/node';
import { handlers } from './handlers';

export const server = setupServer(...handlers);
"""

    browser_content = """// Generated by ODK ignition
// MSW browser worker for development/Storybook
import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
"""

    output = [
        {"path": "mocks/handlers.ts", "content": handlers_content},
        {"path": "mocks/server.ts", "content": server_content},
        {"path": "mocks/browser.ts", "content": browser_content},
    ]

    print(json.dumps(output))


if __name__ == "__main__":
    main()
