#!/usr/bin/env python3
"""Generate FSD feature slices from frontend-features (Next.js App Router).

Input: ODK_COMPONENTS_PAGE (derives features from page mutations/queries)
       or ODK_ARTIFACT_FRONTEND_FEATURES (explicit features file)

Follows Cosden pattern: short focused files, requestHandler for API calls,
typed success/error discrimination, components under 80 lines.
"""

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import yaml
from _context.naming import to_camel, to_pascal


def generate_api_ts(name: str, api_calls: list[str]) -> str:
    """Generate api.ts using requestHandler pattern — typed success/error."""
    if not api_calls:
        return f"""// Generated by ODK ignition
// API calls for {name} feature
// Add your requestHandler calls here:
// import {{ apiClient }} from '@/shared/api/client';
// import {{ requestHandler }} from '@/shared/api/requestHandler';
//
// export const get{to_pascal(name)} = requestHandler(
//   () => apiClient.get('/{name}'),
// );
"""

    lines = [
        "// Generated by ODK ignition",
        f"// API calls for {name} feature",
        "import { apiClient } from '@/shared/api/client';",
        "import { requestHandler } from '@/shared/api/requestHandler';",
        "",
    ]
    for call in api_calls:
        camel_call = to_camel(call)
        lines.append(f"export const {camel_call} = requestHandler(")
        lines.append(f"  () => apiClient.get('/{call.replace('_', '-')}'),")
        lines.append(");")
        lines.append("")
    return "\n".join(lines)


def generate_component_tsx(name: str, component_name: str, description: str, has_form: bool = False) -> str:
    """Generate a focused component under 80 lines."""
    if has_form:
        return _generate_form_component_tsx(name, component_name, description)

    return f"""// Generated by ODK ignition
'use client';
import {{ useState }} from 'react';

type Props = {{
  // TODO: add props
  onSuccess?: () => void;
}};

/**
 * {component_name} — {description or name}
 * Max 80 lines. Extract sub-components if this grows larger.
 */
export function {component_name}({{ onSuccess }}: Props) {{
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (loading) return <div>Loading...</div>;
  if (error) return <div className="text-red-500">{{error}}</div>;

  return (
    <div>
      {{/* ODK-TODO: implement {description or name} UI */}}
    </div>
  );
}}
"""


def _generate_form_component_tsx(name: str, component_name: str, description: str) -> str:
    """Generate a form component using react-hook-form + Zod."""
    schema_name = f"{to_camel(name)}Schema"
    form_type = f"{to_pascal(name)}FormValues"

    return f"""// Generated by ODK ignition
'use client';
import {{ useForm }} from 'react-hook-form';
import {{ zodResolver }} from '@hookform/resolvers/zod';
import {{ z }} from 'zod';
import {{ toast }} from 'sonner';

// TODO: Define validation schema based on your API contract
const {schema_name} = z.object({{
  // Add fields here, e.g.:
  // title: z.string().min(3, 'Title must be at least 3 characters'),
  // description: z.string().max(500).optional(),
}});

type {form_type} = z.infer<typeof {schema_name}>;

type Props = {{
  onSuccess?: () => void;
  defaultValues?: Partial<{form_type}>;
}};

/**
 * {component_name} — {description or name}
 * Uses react-hook-form + Zod for type-safe form handling.
 */
export function {component_name}({{ onSuccess, defaultValues }}: Props) {{
  const {{
    register,
    handleSubmit,
    formState: {{ errors, isSubmitting }},
  }} = useForm<{form_type}>({{
    resolver: zodResolver({schema_name}),
    defaultValues,
  }});

  async function onSubmit(data: {form_type}) {{
    try {{
      // ODK-TODO: call mutation hook
      toast.success('{description or name} completed');
      onSuccess?.();
    }} catch (err) {{
      toast.error('Something went wrong');
    }}
  }}

  return (
    <form onSubmit={{handleSubmit(onSubmit)}} className="space-y-4">
      {{/* ODK-TODO: add form fields using register() */}}
      {{/* Example:
        <input {{...register('title')}} />
        {{errors.title && <p className="text-sm text-destructive">{{errors.title.message}}</p>}}
      */}}
      <button type="submit" disabled={{isSubmitting}}>
        {{isSubmitting ? 'Submitting...' : 'Submit'}}
      </button>
    </form>
  );
}}
"""


def _derive_domain(feature: dict) -> str:
    """Derive the domain group for a feature.

    Uses explicit 'domain' field if present, otherwise infers from
    the feature's route or API call paths.
    """
    if feature.get("domain"):
        return feature["domain"]

    # Try to infer from route
    route = feature.get("route", "")
    if route:
        parts = route.strip("/").split("/")
        # Skip 'api' prefix
        if parts and parts[0] == "api":
            parts = parts[1:]
        if parts:
            return parts[0]

    # Try to infer from api_calls
    api_calls = feature.get("api_calls", [])
    if api_calls:
        # First API call path might indicate domain
        call = api_calls[0]
        parts = call.strip("/").split("/")
        if parts and parts[0] == "api":
            parts = parts[1:]
        if parts:
            return parts[0].replace("_", "-")

    # Fall back to feature name prefix
    name = feature.get("name", "")
    parts = name.split("-")
    if len(parts) > 1:
        return parts[0]

    return "shared"


def generate_feature(feature: dict) -> list[dict]:
    name = feature["name"]
    component_name = to_pascal(name)
    api_calls = feature.get("api_calls", [])
    description = feature.get("description", "")
    has_form = feature.get("form", False)

    # Group under domain directory
    domain = _derive_domain(feature)

    # Derive the sub-feature name (strip domain prefix if present)
    sub_name = name
    domain_prefix = domain.replace("-", "_") + "-"
    name_normalized = name.replace("-", "_") + "-"
    if name_normalized.startswith(domain_prefix.replace("-", "_")):
        sub_name = name[len(domain_prefix.rstrip("-")) :]
        sub_name = sub_name.lstrip("-").lstrip("_") or name

    base_path = f"{domain}/{sub_name}"

    files = []

    # index.ts barrel export
    files.append(
        {
            "path": f"{base_path}/index.ts",
            "content": f"""// Generated by ODK ignition
export {{ {component_name} }} from './{component_name}';
""",
        }
    )

    # api.ts — requestHandler pattern
    files.append(
        {
            "path": f"{base_path}/api.ts",
            "content": generate_api_ts(name, api_calls),
        }
    )

    # Main component (no separate model.ts — keep logic inline per Cosden pattern)
    files.append(
        {
            "path": f"{base_path}/{component_name}.tsx",
            "content": generate_component_tsx(name, component_name, description, has_form),
        }
    )

    return files


def _normalize_feature(raw: dict) -> dict:
    """Normalize new frontend_features schema (id/title/queries/mutations) to generator schema (name/api_calls)."""
    if "name" in raw:
        return raw  # already in old format
    return {
        "name": raw.get("id", ""),
        "description": raw.get("title", ""),
        # queries + mutations become api_calls for domain inference
        "api_calls": raw.get("queries", []) + raw.get("mutations", []),
        "events": raw.get("events", []),
        "sse_source": raw.get("sse_source", ""),
        "form": raw.get("form", False),
    }


def main() -> None:
    # Try explicit frontend features artifact first
    path = os.environ.get("ODK_ARTIFACT_FRONTEND_FEATURES", "")
    if not path or not Path(path).exists():
        # No explicit features — nothing to generate
        print(json.dumps([]))
        return

    data = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    # Support both old schema (features[]) and new schema (frontend_features[])
    raw_features = data.get("frontend_features") or data.get("features", [])
    output = []
    for raw in raw_features:
        feature = _normalize_feature(raw)
        if feature.get("name"):
            output.extend(generate_feature(feature))
    print(json.dumps(output))


if __name__ == "__main__":
    main()
