#!/usr/bin/env python3
"""
Generator: page-containers
Generates smart container components from page components.
Input: ODK_COMPONENTS_PAGE
Output: src/_pages/{page-id}/index.tsx per page
"""

import json
import os
import re
import sys
from pathlib import Path

import yaml


def page_id_to_pascal(page_id: str) -> str:
    return "".join(p.capitalize() for p in re.split(r"[-_]", page_id) if p)


def _derive_page_id(page: dict) -> str:
    """Derive a page identifier from an ODK page component."""
    component_id = page.get("id", "")
    if component_id and "/" in component_id:
        return component_id.rsplit("/", 1)[1]
    if component_id and ":" in component_id:
        return component_id.split(":")[-1]
    return component_id or page.get("name", "")


def hook_to_domain(hook_name: str) -> str:
    """Derive the domain module name from a hook name like useStrategies -> strategies."""
    # Remove leading 'use', lowercase first char
    without_use = hook_name[3:] if hook_name.startswith("use") else hook_name
    # Convert camelCase to kebab-case
    s1 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", without_use)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s1).lower()


def collect_hooks(page: dict) -> list[str]:
    """Collect all hook names from a page definition."""
    hooks = []
    for item in page.get("data", []):
        hook = item.get("hook", "")
        if hook and hook not in hooks:
            hooks.append(hook)
    for item in page.get("sse", []):
        hook = item.get("hook", "")
        if hook and hook not in hooks:
            hooks.append(hook)
    for item in page.get("mutations", []):
        hook = item.get("hook", "")
        if hook and hook not in hooks:
            hooks.append(hook)
    return hooks


def group_hooks_by_domain(hooks: list[str]) -> dict[str, list[str]]:
    """Group hooks by their domain module."""
    groups: dict[str, list[str]] = {}
    for hook in hooks:
        domain = hook_to_domain(hook)
        groups.setdefault(domain, []).append(hook)
    return groups


def generate_container(page: dict) -> str:
    page_id = _derive_page_id(page)
    component_name = f"{page_id_to_pascal(page_id)}Page"

    data_hooks = [item.get("hook", "") for item in page.get("data", []) if item.get("hook")]
    sse_hooks = [item.get("hook", "") for item in page.get("sse", []) if item.get("hook")]
    mutation_hooks = [item.get("hook", "") for item in page.get("mutations", []) if item.get("hook")]
    all_hooks = data_hooks + sse_hooks + mutation_hooks

    # Group hooks by domain for imports
    hook_groups = group_hooks_by_domain(all_hooks)

    lines = [
        "// Generated by ODK ignition",
        "'use client'",
        "",
    ]

    # Import hooks grouped by domain
    for domain, hooks in sorted(hook_groups.items()):
        hooks_str = ", ".join(hooks)
        lines.append(f"import {{ {hooks_str} }} from '@/shared/hooks/{domain}'")

    lines += [
        "import { PageSkeleton } from '@/shared/ui/page-skeleton'",
        "import { ErrorState } from '@/shared/ui/error-state'",
        "",
        f"export function {component_name}() {{",
    ]

    # Primary data hook calls (first data hook drives loading/error state)
    primary_data_hook = data_hooks[0] if data_hooks else None
    for item in page.get("data", []):
        hook = item.get("hook", "")
        if not hook:
            continue
        args = item.get("args", [])
        var_name = hook[3].lower() + hook[4:] if len(hook) > 3 else hook  # useStrategies -> strategies
        args_str = ", ".join(str(a) for a in args)

        if hook == primary_data_hook:
            lines.append(f"  const {{ data: {var_name}, isLoading, error }} = {hook}({args_str})")
        else:
            lines.append(f"  const {{ data: {var_name} }} = {hook}({args_str})")

    # SSE hooks
    for item in page.get("sse", []):
        hook = item.get("hook", "")
        if not hook:
            continue
        args = item.get("args", [])
        args_str = ", ".join(str(a) for a in args)
        var_name = hook[3].lower() + hook[4:] if len(hook) > 3 else hook
        lines.append(f"  const {{ data: {var_name} }} = {hook}({args_str})")

    # Mutation hooks
    for item in page.get("mutations", []):
        hook = item.get("hook", "")
        if not hook:
            continue
        var_name = hook[3].lower() + hook[4:] if len(hook) > 3 else hook
        lines.append(f"  const {var_name} = {hook}()")

    lines.append("")

    if primary_data_hook:
        lines += [
            "  if (isLoading) return <PageSkeleton />",
            "  if (error) return <ErrorState error={error} />",
            "",
        ]

    # Available data comment
    available_data = []
    for item in page.get("data", []):
        hook = item.get("hook", "")
        if hook:
            var_name = hook[3].lower() + hook[4:] if len(hook) > 3 else hook
            available_data.append(var_name)

    data_comment = ", ".join(available_data) if available_data else "none"
    lines += [
        f"  // ODK-TODO: compose widgets for page '{page_id}'",
        f"  // Available data: {data_comment}",
        f"  throw new Error('{component_name} not implemented')",
        "}",
        "",
    ]

    return "\n".join(lines)


def main() -> None:
    pages_path = os.environ.get("ODK_COMPONENTS_PAGE", "")
    if not pages_path or not Path(pages_path).exists():
        print("Warning: ODK_COMPONENTS_PAGE not set or file missing — page-containers skipped.", file=sys.stderr)
        print(json.dumps([]))
        return

    # ODK passes a plain YAML list of page components
    pages = yaml.safe_load(Path(pages_path).read_text(encoding="utf-8")) or []
    if isinstance(pages, dict):
        pages = pages.get("pages", [])

    output = []
    for page in pages:
        page_id = _derive_page_id(page)
        content = generate_container(page)
        output.append({"path": f"{page_id}/index.tsx", "content": content})

    print(json.dumps(output))


if __name__ == "__main__":
    main()
