#!/usr/bin/env python3
"""Guard plugin: block manual edits to proof files.

Proof files are generated by `ydk task done`. Only summary.md is allowed
to be edited by agents.
"""

import json
import sys


def main() -> None:
    """Run the guard-no-proof-tamper check."""
    try:
        raw = sys.stdin.read()
        context = json.loads(raw) if raw.strip() else {}
    except (json.JSONDecodeError, OSError):
        print(
            json.dumps(
                {"name": "guard-no-proof-tamper", "passed": True, "output": "PASS: stdin parse failed (fail open)"}
            )
        )
        return
    file_path = context.get("file_path", "")

    if file_path.startswith(".ydk/proofs/"):
        # Exception: summary.md is allowed
        if file_path.endswith("summary.md"):
            result = {
                "name": "guard-no-proof-tamper",
                "passed": True,
                "output": "OK — summary.md is allowed",
                "duration_seconds": 0.0,
            }
            json.dump(result, sys.stdout)
            sys.exit(0)

        result = {
            "name": "guard-no-proof-tamper",
            "passed": False,
            "output": "BLOCKED: Proof files are generated by `ydk task done`. Do not edit manually.",
            "duration_seconds": 0.0,
        }
        json.dump(result, sys.stdout)
        sys.exit(1)

    result = {
        "name": "guard-no-proof-tamper",
        "passed": True,
        "output": "OK",
        "duration_seconds": 0.0,
    }
    json.dump(result, sys.stdout)
    sys.exit(0)


if __name__ == "__main__":
    main()
