#!/usr/bin/env python3
"""
Generator: fake-ports
Generate Fake{PortName} adapter classes for every non-repository port.
Input: ports.yaml
Output: tests/fakes/fake_{port_snake}.py per custom port
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

# Add generators dir to path for _context imports
sys.path.insert(0, str(Path(__file__).parent))

import yaml
from _context.naming import derive_name, port_module_name, to_snake
from jinja2 import Environment, FileSystemLoader, StrictUndefined

TYPE_MAP = {
    "str": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
    "uuid": "UUID",
    "datetime": "datetime",
    "date": "date",
    "bytes": "bytes",
    "json": "dict[str, Any]",
    "None": "None",
    "any": "Any",
    "Decimal": "Decimal",
    "decimal": "Decimal",
    "void": "None",
    "callable": "Any",
}

PRIMITIVES = {
    "str",
    "int",
    "float",
    "bool",
    "uuid",
    "datetime",
    "date",
    "bytes",
    "json",
    "None",
    "Any",
    "Decimal",
    "void",
    "callable",
}


def map_type(t: str) -> str:
    """Map artifact type names to Python type annotations."""
    t = t.strip()
    if t.startswith("optional["):
        return f"{map_type(t[9:-1])} | None"
    if t.startswith("list["):
        return f"list[{map_type(t[5:-1])}]"
    # Handle "Type|null" and "Type | None" nullable patterns
    if "|null" in t:
        return f"{map_type(t.replace('|null', '').strip())} | None"
    if " | None" in t:
        return f"{map_type(t.replace(' | None', '').strip())} | None"
    mapped = TYPE_MAP.get(t, t)
    # Entity types (capitalized, not a known primitive) get Model suffix to match port protocol
    if mapped == t and t and t[0].isupper() and t not in PRIMITIVES:
        if not mapped.endswith("Model"):
            return f"{mapped}Model"
    return mapped


def _default_for_type(t: str) -> str:
    """Return a sensible default return value for a mapped Python type."""
    t = t.strip()
    if t == "None":
        return "None"
    if t.endswith("| None"):
        return "None"
    if t.startswith("list[") or t.startswith("_List["):
        return "[]"
    if t.startswith("dict[") or t == "dict":
        return "{}"
    if t == "str":
        return '""'
    if t in ("int", "float"):
        return "0"
    if t == "bool":
        return "False"
    if t == "bytes":
        return 'b""'
    if t == "Any":
        return "None"
    # For entity/model types, return None (caller should handle optional)
    return "None  # type: ignore[return-value]"


def is_repository_port(port_name: str) -> bool:
    """Return True if the port is a repository port (generated by fake_repos.py)."""
    return port_name.endswith("RepositoryPort")


def _extract_entity_names(mapped_type: str) -> set[str]:
    """Extract entity type names (ending in Model) from a mapped Python type annotation."""
    entities: set[str] = set()
    # Strip wrapper syntax: list[...], dict[...], ... | None
    cleaned = mapped_type.replace("| None", "").strip()
    # Remove list[...] and dict[...] wrappers
    for prefix in ("list[", "_List[", "dict["):
        if cleaned.startswith(prefix):
            cleaned = cleaned[len(prefix) : -1]
    # Split on commas (for dict[K, V])
    parts = [p.strip() for p in cleaned.split(",")]
    known_primitives = {"str", "int", "float", "bool", "bytes", "None", "Any", "UUID", "datetime", "date", "object"}
    for part in parts:
        if part and part not in known_primitives and part[0].isupper() and part.endswith("Model"):
            entities.add(part)
    return entities


def build_fake_port_context(port: dict) -> dict:
    """Build the Jinja2 template context for one fake port adapter."""
    name = port["name"]
    # Strip trailing "Port" for the class name: NotificationPort -> FakeNotification
    bare_name = name.removesuffix("Port") if name.endswith("Port") else name
    methods_raw = port.get("methods", [])

    imports: set[str] = {"from __future__ import annotations"}
    extra_imports: set[str] = set()
    entity_names: set[str] = set()

    # Build methods
    methods = []
    needs_list_alias = False
    for m in methods_raw:
        mname = m["name"]
        args = m.get("args", [])
        returns = map_type(m.get("returns", "None"))
        is_async = m.get("async", True)

        # Collect type imports from args and return type
        all_types = [map_type(a.get("type", "")) for a in args] + [returns]
        for mapped in all_types:
            if "UUID" in mapped:
                extra_imports.add("from uuid import UUID")
            if "Decimal" in mapped:
                extra_imports.add("from decimal import Decimal")
            if "datetime" in mapped and "import datetime" not in str(extra_imports):
                extra_imports.add("from datetime import datetime")
            if "date" in mapped and "datetime" not in mapped:
                extra_imports.add("from datetime import date")
            if "Any" in mapped:
                extra_imports.add("from typing import Any")
            # Collect domain entity types that need model imports
            entity_names |= _extract_entity_names(mapped)

        arg_str = ", ".join(f"{a['name']}: {map_type(a['type'])}" for a in args)
        if arg_str:
            arg_str = ", " + arg_str
        prefix = "async def" if is_async else "def"

        # Handle list alias for methods named "list"
        display_returns = returns
        if mname == "list" and returns.startswith("list["):
            display_returns = returns.replace("list[", "_List[", 1)
            needs_list_alias = True

        default = _default_for_type(returns)

        methods.append(
            {
                "name": mname,
                "prefix": prefix,
                "arg_str": arg_str,
                "returns": display_returns,
                "default": default,
            }
        )

    # Build import block (no port import — fakes use duck typing, not inheritance)
    imports |= extra_imports

    # Add imports for domain entity types (e.g. StrategyModel -> from app.core.models.strategy import StrategyModel)
    for model_cls in sorted(entity_names):
        # model_cls is e.g. "StrategyModel" — derive module from entity name
        entity_name = model_cls.removesuffix("Model")
        snake = to_snake(entity_name)
        imports.add(f"from app.core.models.{snake} import {model_cls}")

    # Sort imports: __future__ -> stdlib -> first-party
    future_imps = sorted(i for i in imports if i.startswith("from __future__"))
    stdlib_imps = sorted(i for i in imports if not i.startswith("from __future__") and not i.startswith("from app."))
    firstparty_imps = sorted(i for i in imports if i.startswith("from app."))
    groups = [g for g in [future_imps, stdlib_imps, firstparty_imps] if g]
    import_block = "\n\n".join("\n".join(g) for g in groups)

    return {
        "port_name": name,
        "bare_name": bare_name,
        "import_block": import_block,
        "methods": methods,
        "needs_list_alias": needs_list_alias,
    }


def _normalize_standalone_port(contract: dict) -> dict | None:
    """Convert a standalone port contract to the format expected by build_fake_port_context.

    Standalone port contracts have their name ending in "Port" and methods at top level
    in dict format: {method_name: {params: {...}, returns: {...}}}.
    Returns None if not a standalone port contract.
    """
    name = derive_name(contract)
    if not name.endswith("Port"):
        return None
    # Must have methods at top level and NOT have a 'ports' field
    if contract.get("ports"):
        return None
    methods_raw = contract.get("methods", {})
    if not methods_raw or not isinstance(methods_raw, dict):
        return None

    # Convert dict-format methods to list-format expected by build_fake_port_context
    methods = []
    for mname, mdef in methods_raw.items():
        if not isinstance(mdef, dict):
            mdef = {}
        # Convert params dict to args list
        params = mdef.get("params", {})
        args = []
        if isinstance(params, dict):
            for pname, pdef in params.items():
                if isinstance(pdef, dict):
                    ptype = pdef.get("type", "str")
                else:
                    ptype = str(pdef) if pdef else "str"
                args.append({"name": pname, "type": ptype})
        elif isinstance(params, list):
            args = params
        # Extract return type
        returns = mdef.get("returns", {})
        if isinstance(returns, dict):
            ret_type = returns.get("type", "None")
        else:
            ret_type = str(returns) if returns else "None"
        methods.append(
            {
                "name": mname,
                "args": args,
                "returns": ret_type,
                "async": mdef.get("async", True),
            }
        )

    return {"name": name, "methods": methods}


def main() -> None:
    path = os.environ.get("ODK_COMPONENTS_CONTRACT", "")
    if not path or not Path(path).exists():
        print("[]")
        return

    data = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    # ODK format: contracts is a list, ports are nested in each contract
    contracts = data if isinstance(data, list) else []
    ports = [port for contract in contracts for port in contract.get("ports", [])]

    # Also handle standalone port contracts (contract IS the port, name ends in "Port")
    for contract in contracts:
        standalone = _normalize_standalone_port(contract)
        if standalone:
            ports.append(standalone)

    # Set up Jinja2
    templates_dir = Path(__file__).parent.parent / "templates" / "tests"
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    template = env.get_template("fake_port.py.j2")

    output = []
    for port in ports:
        if is_repository_port(port["name"]):
            continue
        context = build_fake_port_context(port)
        content = template.render(**context).rstrip() + "\n"
        port_module = port_module_name(port["name"])
        output.append({"path": f"tests/fakes/fake_{port_module}.py", "content": content})

    print(json.dumps(output))


if __name__ == "__main__":
    main()
