// Sample FSD feature component generated by the nextjs-fsd-shadcn ignition pack.
// This illustrates the structure a generator would produce.
'use client';
import { useState } from 'react';

type Props = {
  onSuccess?: () => void;
};

/**
 * ExampleFeature -- sample feature stub.
 * Max 80 lines. Extract sub-components if this grows larger.
 */
export function ExampleFeature({ onSuccess }: Props) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (loading) return <div>Loading...</div>;
  if (error) return <div className="text-red-500">{error}</div>;

  return (
    <div>
      {/* TODO: implement feature UI */}
    </div>
  );
}
